version: "3.9"

services:
  bot:
    build: .
    container_name: medical_bot
    restart: always

    env_file:
      - .env
    volumes:
      - bot_data:/app/data
    
    command: python bot.py

volumes:
  bot_data:
